attr_fn_like_width=80
brace_style="SameLineWhere"
chain_width=80
control_brace_style="AlwaysSameLine"
comment_width=80
error_on_line_overflow=true
fn_args_layout="Tall"
fn_call_width=80
fn_params_layout="Tall"
format_code_in_doc_comments=true
group_imports="StdExternalCrate"
hard_tabs=false
imports_granularity="Module"
indent_style="Block"
max_width=100
merge_derives=true
newline_style="Unix"
normalize_comments=true
remove_nested_parens=true
reorder_impl_items=true
reorder_imports=true
reorder_modules=true
single_line_if_else_max_width=80
space_after_colon=true
spaces_before_color=false
spaces_around_ranges=false
tab_spaces=4
trailing_comma="Vertical"
unstable_features=true
use_field_init_shorthand=true
use_small_heuristics="Default"
where_single_line=true
wrap_comments=true
